baseURL = "https://santa-sukitoku.github.io/santa-diary/"
title = "santa-diary"
author = "santa_sukitoku"
theme = "kiss"
publishDir = "docs"
hasCJKLanguage = true
DefaultContentLanguage = "ja"
languageCode = "ja-JP"
copyright = "&copy; <a href=\"https://github.com/ribice\">Emir Ribic</a> 2017"
Paginate = 10 # Number of posts per page
enableRobotsTXT = true

[params.assets]
customCSS = ["css/custom.css"]

[params.info]
adsense = "" # Adsense ID (ID only, without ca-pub-)
enableSocial = true # Adds OpenGraph and Twitter cards
homeTitle = "santa-diary" # Title for home page
poweredby = true # Adds powered by hugo and kiss below Copyright
related = true # Includes related articles at the bottom of the article
codeCopy = true # Add copy button above code blocks

[params.features]
disqusOnDemand = true  # Load Disqus comments on click

[params.social]
twitter = "santa_sukitoku"
github = "santa-sukitoku"
instagram = "santa_sukitoku"

[params.social.config]
platforms = ["twitter","github","instagram"]

[params.sections_left]
"https://santa-sukitoku.github.io/about.html" = "about"
"https://santa-sukitoku.github.io/portfolio.html" = "portfolio"

[taxonomies]
tag ="tags"

[blackfriday]
hrefTargetBlank = true