baseURL = "https://santa-sukitoku.github.io/santa-log/"
title = "santa-log"
author = "santa_sukitoku"
theme = "ezhil"
canonifyurls = true
paginate = 3
publishDir = "docs"
hasCJKLanguage = true
DefaultContentLanguage = "ja"
languageCode = "ja-JP"

pygmentsstyle = "vs"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

googleAnalytics = "UA-123-45"
disqusShortname = "localhost"

[params]
	subtitle = "Diary"
	# Number of posts to show in recent posts list.
	recentPostsCount = 10
	# Content types which are excluded from recent posts and archive page.
	excludedTypes = ["page"]
	disableDisqusTypes = ["page"]
	featherIconsCDN = true

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "About"
url = "https://santa-sukitoku.github.io/"
weight = 2

[[menu.main]]
name = "Portfolio"
url = "https://santa-sukitoku.github.io/santa-portfolio/"
weight = 3

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 4

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 5

[[params.social]]
name = "Twitter"
icon = "twitter"
url = "https://twitter.com/santa_sukitoku"

[[params.social]]
name = "Github"
icon = "github"
url = "https://github.com/santa-sukitoku"

[[params.social]]
name = "SoundCloud"
icon = "volume-2"
url = "https://soundcloud.com/santa-n"

[taxonomies]
   tag = "tags"

